name: storage-builder
on:
  # push:
  #   branches:
  #     - master
  workflow_dispatch:

jobs:
  build:
    name: build the binary
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: uraimo/run-on-arch-action@v2.0.5
      name: Build artifact
      id: build
      with:
        arch: aarch64
        distro: ubuntu18.04
        setup: |
            mkdir -p "${PWD}/artifacts"
        dockerRunArgs: |
          --volume "${PWD}/artifacts:/artifacts"
        run: |
          apt update
          apt -y install --no-install-recommends curl wget ca-certificates
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.37.2/install.sh | bash
          . ~/.nvm/nvm.sh
          nvm install 12.18.1
          npm ci
          mkdir -p ~/.pkg-cache/v2.6
          wget https://github.com/robertsLando/pkg-binaries/releases/download/v1.0.0/fetched-v12.18.1-linux-arm64 -O fetched-v12.18.1-linux-arm64
          mv fetched-v12.18.1-linux-arm64 ~/.pkg-cache/v2.6
          npm run build
          npm run pkg -- --targets node12-linux-arm64 --output storage-api-arm64
          cp storage-api-arm64 /artifacts/storage-api-arm64
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: /artifacts/storage-api-arm64
        tag_name: 0.0.1
        name: test-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      